# Generated by Django 5.0.6 on 2024-06-27 10:25

from django.db import migrations


def create_initial_listings(apps, schema_editor):
    Listing = apps.get_model('autohaven_app', 'Listing')
    User = apps.get_model('auth', 'User')

    # Fetch users
    seller_user = User.objects.get(username='seller')
    regular_user = User.objects.get(username='regularuser')
    bedi_user = User.objects.get(username='bediuser')  # Fetch the new user

    # New Cars
    new_cars = [
        {
            "title": "Tesla On the Market",
            "type": "new",
            "model": "Model Y",
            "year": 2023,
            "brand": "Tesla",
            "mileage": 0,
            "engine_type": "Electric",
            "body_type": "Hatchback",
            "price": 80000,
            "description": (
                "The Tesla Model Y is an all-electric compact crossover SUV that "
                "combines the performance and innovation Tesla is known for with the "
                "versatility of an SUV. Launched in 2020, it is designed to offer a "
                "spacious and high-tech driving experience while maintaining the impressive "
                "acceleration and efficiency that Tesla vehicles are celebrated for."
            ),
        },
        {
            "title": "BMW M3 Performance",
            "type": "new",
            "model": "M3",
            "year": 2024,
            "brand": "BMW",
            "mileage": 0,
            "engine_type": "Inline 6",
            "body_type": "Sedan",
            "price": 70000,
            "description": (
                "The new BMW M3 offers a thrilling driving experience with its turbocharged "
                "inline-six engine and precise handling. It combines luxury and performance, "
                "making it a top choice for enthusiasts who crave the ultimate sports sedan."
            ),
        },
        {
            "title": "Audi Q8 Luxury",
            "type": "new",
            "model": "Q8",
            "year": 2024,
            "brand": "Audi",
            "mileage": 0,
            "engine_type": "Turbocharged 4-cylinder",
            "body_type": "SUV",
            "price": 50000,
            "description": (
                "The 2024 Audi Q8 delivers a balanced mix of performance, comfort, and technology. "
                "With a spacious interior, smooth ride, and a suite of advanced features, the Q8 is "
                "perfect for families or anyone looking for a luxurious SUV experience."
            ),
        },
        {
            "title": "Mercedes-Benz E-Class",
            "type": "new",
            "model": "E-Class",
            "year": 2024,
            "brand": "Mercedes-Benz",
            "mileage": 0,
            "engine_type": "V6",
            "body_type": "Sedan",
            "price": 60000,
            "description": (
                "The new Mercedes-Benz E-Class offers elegance and sophistication. With its powerful V6 engine, "
                "state-of-the-art interior, and cutting-edge safety features, it sets a high standard for luxury sedans."
            ),
        },
        {
            "title": "Ford Mustang GT",
            "type": "new",
            "model": "Mustang GT",
            "year": 2024,
            "brand": "Ford",
            "mileage": 0,
            "engine_type": "V8",
            "body_type": "Coupe",
            "price": 55000,
            "description": (
                "The 2024 Ford Mustang GT is an iconic muscle car, equipped with a roaring V8 engine and aggressive styling. "
                "It offers exhilarating performance and a modernized interior with the latest tech features."
            ),
        },
        {
            "title": "Chevrolet Corvette",
            "type": "new",
            "model": "Corvette",
            "year": 2024,
            "brand": "Chevrolet",
            "mileage": 0,
            "engine_type": "V8",
            "body_type": "Convertible",
            "price": 75000,
            "description": (
                "The Chevrolet Corvette is a legendary sports car that offers breathtaking speed and handling. "
                "Its sleek design and convertible option make it a dream car for enthusiasts."
            ),
        },
        {
            "title": "Porsche 911 Carrera",
            "type": "new",
            "model": "911 Carrera",
            "year": 2024,
            "brand": "Porsche",
            "mileage": 0,
            "engine_type": "Flat 6",
            "body_type": "Coupe",
            "price": 90000,
            "description": (
                "The 2024 Porsche 911 Carrera is a masterclass in automotive engineering. "
                "With its rear-engine layout and sublime handling, it continues to set benchmarks in the sports car world."
            ),
        },
        {
            "title": "Lexus RX 350",
            "type": "new",
            "model": "RX 350",
            "year": 2024,
            "brand": "Lexus",
            "mileage": 0,
            "engine_type": "V6",
            "body_type": "SUV",
            "price": 50000,
            "description": (
                "The new Lexus RX 350 offers a blend of luxury, comfort, and performance. "
                "With its refined V6 engine and plush interior, it delivers a smooth ride for all passengers."
            ),
        },
        {
            "title": "Jaguar XF",
            "type": "new",
            "model": "XF",
            "year": 2024,
            "brand": "Jaguar",
            "mileage": 0,
            "engine_type": "Turbocharged 4-cylinder",
            "body_type": "Sedan",
            "price": 65000,
            "description": (
                "The 2024 Jaguar XF exudes style and elegance. "
                "Its agile handling and advanced technology make it a standout in the luxury sedan segment."
            ),
        },
        {
            "title": "Volvo XC90",
            "type": "new",
            "model": "XC90",
            "year": 2024,
            "brand": "Volvo",
            "mileage": 0,
            "engine_type": "Turbocharged 4-cylinder",
            "body_type": "SUV",
            "price": 55000,
            "description": (
                "The Volvo XC90 is known for its safety features and Scandinavian design. "
                "With its spacious cabin and cutting-edge technology, it offers a premium SUV experience."
            ),
        },
        {
            "title": "Hyundai Ioniq 5",
            "type": "new",
            "model": "Ioniq 5",
            "year": 2024,
            "brand": "Hyundai",
            "mileage": 0,
            "engine_type": "Electric",
            "body_type": "Crossover",
            "price": 45000,
            "description": (
                "The Hyundai Ioniq 5 is a futuristic all-electric crossover that offers impressive range and innovative features. "
                "Its eco-friendly design and spacious interior make it an excellent choice for modern drivers."
            ),
        }
    ]

    # Used Cars
    used_cars_regular = [
        {
            "title": "Wrangler In Great Condition",
            "type": "used",
            "model": "Wrangler",
            "year": 2020,
            "brand": "Jeep",
            "mileage": 1000,
            "engine_type": "Pentastar V6",
            "body_type": "SUV",
            "price": 80000,
            "description": (
                "Get ready to conquer the open road or rugged terrain with this 2017 Jeep Wrangler Unlimited Sahara. "
                "This versatile SUV combines classic Jeep ruggedness with modern comforts, making it an ideal choice for "
                "adventure seekers and urban drivers alike. With its iconic design and off-road capabilities, this used "
                "Wrangler is ready for your next journey."
            ),
        },
        {
            "title": "Ford F-150 Workhorse",
            "type": "used",
            "model": "F-150",
            "year": 2019,
            "brand": "Ford",
            "mileage": 45000,
            "engine_type": "V8",
            "body_type": "Truck",
            "price": 30000,
            "description": (
                "The 2019 Ford F-150 is a reliable truck that's ready for any job. "
                "With a strong V8 engine and a spacious interior, it's perfect for both work and play."
            ),
        },
        {
            "title": "Chevrolet Tahoe Family SUV",
            "type": "used",
            "model": "Tahoe",
            "year": 2018,
            "brand": "Chevrolet",
            "mileage": 55000,
            "engine_type": "V8",
            "body_type": "SUV",
            "price": 35000,
            "description": (
                "The Chevrolet Tahoe is a full-size SUV that offers ample space for the whole family. "
                "With a strong engine and a comfortable ride, it's ideal for both city and highway driving."
            ),
        },
        {
            "title": "Nissan Altima Reliable",
            "type": "used",
            "model": "Altima",
            "year": 2019,
            "brand": "Nissan",
            "mileage": 22000,
            "engine_type": "Inline 4",
            "body_type": "Sedan",
            "price": 17000,
            "description": (
                "The 2019 Nissan Altima provides a smooth ride with advanced safety features. "
                "It's a great choice for those looking for a reliable and efficient daily driver."
            ),
        },
        {
            "title": "Kia Sportage Comfort",
            "type": "used",
            "model": "Sportage",
            "year": 2018,
            "brand": "Kia",
            "mileage": 45000,
            "engine_type": "Inline 4",
            "body_type": "SUV",
            "price": 19000,
            "description": (
                "This 2018 Kia Sportage offers comfort and reliability, making it an excellent choice for families. "
                "With its spacious interior and smooth ride, it's ready for any journey."
            ),
        }
    ]

    used_cars_bediuser = [
        {
            "title": "Toyota Camry SE",
            "type": "used",
            "model": "Camry",
            "year": 2018,
            "brand": "Toyota",
            "mileage": 30000,
            "engine_type": "Inline 4",
            "body_type": "Sedan",
            "price": 20000,
            "description": (
                "The 2018 Toyota Camry SE offers a balance of style and efficiency. "
                "It's a dependable sedan with a comfortable interior and great fuel economy, ideal for daily commuting."
            ),
        },
        {
            "title": "Honda Accord LX",
            "type": "used",
            "model": "Accord",
            "year": 2017,
            "brand": "Honda",
            "mileage": 25000,
            "engine_type": "Inline 4",
            "body_type": "Sedan",
            "price": 18000,
            "description": (
                "This 2017 Honda Accord LX offers a comfortable ride with great fuel efficiency. "
                "It's a well-maintained vehicle that provides a blend of style and practicality."
            ),
        },
        {
            "title": "Mazda CX-5 Compact SUV",
            "type": "used",
            "model": "CX-5",
            "year": 2017,
            "brand": "Mazda",
            "mileage": 32000,
            "engine_type": "Inline 4",
            "body_type": "SUV",
            "price": 21000,
            "description": (
                "The 2017 Mazda CX-5 is a stylish compact SUV that offers an engaging driving experience. "
                "With a well-designed interior and excellent fuel economy, it's a great choice for those who value performance and style."
            ),
        },
        {
            "title": "Volkswagen Golf GTI",
            "type": "used",
            "model": "Golf GTI",
            "year": 2018,
            "brand": "Volkswagen",
            "mileage": 40000,
            "engine_type": "Turbocharged Inline 4",
            "body_type": "Hatchback",
            "price": 23000,
            "description": (
                "This 2018 Volkswagen Golf GTI is a sporty hatchback that offers lively performance and a fun-to-drive character. "
                "With its turbocharged engine and agile handling, it's perfect for enthusiasts who enjoy a spirited drive."
            ),
        },
        {
            "title": "Subaru Outback Adventure",
            "type": "used",
            "model": "Outback",
            "year": 2017,
            "brand": "Subaru",
            "mileage": 60000,
            "engine_type": "Flat 4",
            "body_type": "SUV",
            "price": 20000,
            "description": (
                "The 2017 Subaru Outback is built for adventure, with all-wheel drive and a spacious interior. "
                "It's a versatile SUV that's perfect for those who love exploring both on and off the road."
            ),
        }
    ]

    # Create new car listings
    for car in new_cars:
        Listing.objects.create(
            title=car["title"],
            type=car["type"],
            model=car["model"],
            year=car["year"],
            brand=car["brand"],
            mileage=car["mileage"],
            engine_type=car["engine_type"],
            body_type=car["body_type"],
            price=car["price"],
            sold=False,
            description=car["description"],
            user_id=seller_user.id
        )

    # Create used car listings for regular user
    for car in used_cars_regular:
        Listing.objects.create(
            title=car["title"],
            type=car["type"],
            model=car["model"],
            year=car["year"],
            brand=car["brand"],
            mileage=car["mileage"],
            engine_type=car["engine_type"],
            body_type=car["body_type"],
            price=car["price"],
            sold=False,
            description=car["description"],
            user_id=regular_user.id
        )

    # Create used car listings for bediuser
    for car in used_cars_bediuser:
        Listing.objects.create(
            title=car["title"],
            type=car["type"],
            model=car["model"],
            year=car["year"],
            brand=car["brand"],
            mileage=car["mileage"],
            engine_type=car["engine_type"],
            body_type=car["body_type"],
            price=car["price"],
            sold=False,
            description=car["description"],
            user_id=bedi_user.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('autohaven_app', '0008_create_more_users'),
    ]

    operations = [
        migrations.RunPython(create_initial_listings),
    ]
