# Generated by Django 5.0.6 on 2024-07-11 14:58

from django.db import migrations
from django.conf import settings
import os


def assign_initial_images(apps, schema_editor):
    Listing = apps.get_model('autohaven_app', 'Listing')
    ListingImage = apps.get_model('autohaven_app', 'ListingImage')

    # Define paths to the folders containing initial images
    initial_images_paths = {
        # New cars
        1: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_tesla'),
        2: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_bmw'),
        3: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_audi'),
        4: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_mercedes'),
        5: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_ford'),
        6: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_chevrolet'),
        7: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_porsche'),
        8: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_lexus'),
        9: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_jaguar'),
        10: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_volvo'),
        11: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_hyundai'),

        # Used cars for regular_user
        12: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_jeep'),
        13: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_ford_f150'),
        14: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_chevrolet_tahoe'),
        15: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_nissan_altima'),
        16: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_kia_sportage'),

        # Used cars for bediuser
        17: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_toyota_camry'),
        18: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_honda_accord'),
        19: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_mazda_cx5'),
        20: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_volkswagen_golf'),
        21: os.path.join(settings.BASE_DIR, 'data/uploaded_images/initial_images_subaru_outback'),
    }

    # Iterate through each listing ID and corresponding folder
    for listing_id, images_path in initial_images_paths.items():
        try:
            listing = Listing.objects.get(id=listing_id)
        except Listing.DoesNotExist:
            print(f"Listing with ID {listing_id} does not exist.")
            continue

        # Iterate through the files in the directory
        for filename in os.listdir(images_path):
            if filename.endswith('.jpg') or filename.endswith('.png'):
                image_path = os.path.join(os.path.basename(images_path), filename)
                ListingImage.objects.create(
                    listing=listing,
                    imagepath=image_path,
                )

class Migration(migrations.Migration):

    dependencies = [
        ("autohaven_app", "0009_create_init_listings"),
    ]

    operations = [migrations.RunPython(assign_initial_images),]
